DefaultContentLanguage = "en"
copyright = "Everything is mine"
baseURL = "https://goshva.github.io/qrConstr/"
languageCode = "en-us"
title = "Search fragment in QRcode"
theme = ["snakeword"]

[Languages]
[Languages.en]
  Languagename =  "English"

  title = "qr code with mosaic"
  weight = 1
  author = "Yzoz Sha. Egor"
  Description = "Take a word by side by side letters"
  keywords = "Generator and finder pixel fragment in random QRcode"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "random"
  Setings = "set"
  Save = "Save"
  Cut = "Clear"
  Gen = "Generate"


[Languages.ru]
  Languagename =  "Русский"
  title = "qr-код с мозайкой"
  weight = 2
  author = "Егор Ша. Yzoz"
  Description = "Найдем фрагмент и предоставим qr код его включающий"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Хаос"
  Setings = "Набор"
  Save = "Сохранить"
  Cut = "Стереть"
  Gen = "Сгенерировать"

[Languages.de]
  Languagename =  "Deutsch"
  title = "QR-Code mit Mosaik"
  weight = 2
  author = "Егор Ша."
  Description = "Lassen Sie uns ein Fragment finden und einen QR-Code bereitstellen, der es enthält"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Spiel Typ"
  Random = "Хаос"
  Setings = "Набор"
  Save = "Speichern"
  Cut = "Löschen"
  Gen = "Generieren"
[taxonomies]
  category = "categories"
  tag = "tags"

