DefaultContentLanguage = "en"
copyright = "Everything is mine"
baseURL = "http://snakeword.ru/"
languageCode = "en-us"
title = "My snakeword game"
theme = ["snakeword"]

[Languages]
[Languages.en]
  Languagename =  "English"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "Take a word by side by side letters"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "random"
  Setings = "set"
  Save = "Save"
  Cut = "Clear"
  Gen = "Generate"


[Languages.ru]
  Languagename =  "Русский"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Игра собери слово"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Хаос"
  Setings = "Набор"
  Save = "Сохранить"
  Cut = "Стереть"
  Gen = "Сгенерировать"

[Languages.de]
  Languagename =  "Немецкий"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Игра собери слово"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Хаос"
  Setings = "Набор"
  Save = "Сохранить"
  Cut = "Löschen"
  Gen = "Generieren"
[taxonomies]
  category = "categories"
  tag = "tags"

